[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "chromium", "glib", "libffi", "libgcc", "zlib", "gcc"]

[phases.install]
cmds = [
  "python -m pip install -r requirements.txt",
  "python -m playwright install chromium"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "python bot.py"
